const SIZE=14;
const COST={road:4,rail:6,station:30,power:38,water:34,park:16,bulldoze:1};
const LABEL={road:'道路',rail:'線路',station:'駅',power:'発電所',water:'浄水場',park:'公園',bulldoze:'削除'};
const ICON={station:'駅',power:'電',water:'水',park:'木',house:'家',shop:'店',factory:'工',apartment:'団',tower:'塔'};
const BUILDINGS=['house','shop','factory','apartment','tower'];
const initial=()=>({year:1,money:180,population:0,income:0,selected:'road',pathStart:null,pathMode:'hv',tiles:Array.from({length:SIZE*SIZE},()=>({type:'empty',level:0}))});
let state=initial();
let preview=[];let selectedTile=null;let pressTimer=null;let longPressed=false;
const $=id=>document.getElementById(id);
const mapEl=$('map'),reportEl=$('reportText'),floatEl=$('floatMessage'),radialEl=$('radialMenu');
const yearEl=$('yearValue'),moneyEl=$('moneyValue'),populationEl=$('populationValue'),incomeEl=$('incomeValue'),modeLabel=$('modeLabel'),modeHint=$('modeHint'),tileInfo=$('tileInfoText');
function idx(x,y){return y*SIZE+x}function xy(i){return{x:i%SIZE,y:Math.floor(i/SIZE)}}
function neighbors(i){const{x,y}=xy(i),r=[];if(y>0)r.push(idx(x,y-1));if(x<SIZE-1)r.push(idx(x+1,y));if(y<SIZE-1)r.push(idx(x,y+1));if(x>0)r.push(idx(x-1,y));return r}
function distance(a,b){const p=xy(a),q=xy(b);return Math.abs(p.x-q.x)+Math.abs(p.y-q.y)}
function isTransport(t){return t.type==='road'||t.type==='rail'||t.type==='station'}
function countNear(i,type,r){return state.tiles.reduce((n,t,j)=>n+(t.type===type&&distance(i,j)<=r?1:0),0)}
function supplied(i,type,r){return countNear(i,type,r)>0}
function roadConnected(i){const starts=[];state.tiles.forEach((t,j)=>{if(t.type==='station')starts.push(j)});for(let x=0;x<SIZE;x++){const top=idx(x,0),bottom=idx(x,SIZE-1);if(state.tiles[top].type==='road')starts.push(top);if(state.tiles[bottom].type==='road')starts.push(bottom)}for(let y=0;y<SIZE;y++){const left=idx(0,y),right=idx(SIZE-1,y);if(state.tiles[left].type==='road')starts.push(left);if(state.tiles[right].type==='road')starts.push(right)}if(!starts.length)return neighbors(i).some(j=>state.tiles[j].type==='road');const seen=new Set(starts),q=[...starts];while(q.length){const cur=q.shift();for(const n of neighbors(cur)){if(!seen.has(n)&&(state.tiles[n].type==='road'||state.tiles[n].type==='station')){seen.add(n);q.push(n)}}}return neighbors(i).some(n=>seen.has(n))}
function score(i){let s=0;if(roadConnected(i))s+=3;if(supplied(i,'power',4))s+=2;if(supplied(i,'water',4))s+=2;if(supplied(i,'station',3))s+=2;if(supplied(i,'park',2))s+=1;return s}
function showMessage(text){floatEl.textContent=text;floatEl.classList.add('show');clearTimeout(showMessage.t);showMessage.t=setTimeout(()=>floatEl.classList.remove('show'),1300)}
function save(){localStorage.setItem('infra-king-save-v2',JSON.stringify(state))}
function load(){try{const s=JSON.parse(localStorage.getItem('infra-king-save-v2'));if(s&&s.tiles?.length===SIZE*SIZE)state={...initial(),...s,pathStart:null}}catch(e){console.warn(e)}}
function route(a,b,mode=state.pathMode){const A=xy(a),B=xy(b),out=[];const walk=(x1,y1,x2,y2)=>{let x=x1,y=y1;out.push(idx(x,y));while(x!==x2){x+=Math.sign(x2-x);out.push(idx(x,y))}while(y!==y2){y+=Math.sign(y2-y);out.push(idx(x,y))}};if(mode==='hv')walk(A.x,A.y,B.x,A.y),walk(B.x,A.y,B.x,B.y);else walk(A.x,A.y,A.x,B.y),walk(A.x,B.y,B.x,B.y);return [...new Set(out)]}
function connectionClass(i,type){const dirs=[];const{x,y}=xy(i);const checks=[['n',x,y-1],['e',x+1,y],['s',x,y+1],['w',x-1,y]];for(const[d,nx,ny]of checks){if(nx<0||ny<0||nx>=SIZE||ny>=SIZE)continue;const t=state.tiles[idx(nx,ny)].type;if(t===type||(type==='rail'&&t==='station')||(type==='road'&&t==='station'))dirs.push(d)}if(dirs.length>=3)return dirs.length===4?'cross':'tee';const key=dirs.sort().join('');return({ns:'ns',ew:'ew',en:'ne',nw:'nw',es:'se',sw:'sw',n:'n',e:'e',s:'s',w:'w'}[key]||'ew')}
function updateTileInfo(i){selectedTile=i;const t=state.tiles[i];if(t.type==='empty'){tileInfo.innerHTML=`空き地<br>道路 ${roadConnected(i)?'✓':'✕'}　電気 ${supplied(i,'power',4)?'✓':'✕'}　水 ${supplied(i,'water',4)?'✓':'✕'}<br>発展度 ${score(i)}/10`;}else{tileInfo.textContent=`${LABEL[t.type]||t.type}${t.level>1?` Lv.${t.level}`:''}`}}
function render(){mapEl.innerHTML='';state.tiles.forEach((tile,i)=>{const b=document.createElement('button');b.type='button';let cls=`tile ${tile.type} ${i%2===Math.floor(i/SIZE)%2?'alt':''}`;if(tile.type==='road'||tile.type==='rail')cls+=` ${connectionClass(i,tile.type)}`;if(preview.includes(i))cls+=' preview';if(selectedTile===i)cls+=' selected';if(state.selected==='power'&&distance(i,selectedTile??-99)<=4)cls+=' range';if(tile.type==='empty'&&score(i)>=5)cls+=' developable';b.className=cls;b.dataset.index=i;b.setAttribute('aria-label',`${xy(i).x+1},${xy(i).y+1} ${tile.type}`);const sp=document.createElement('span');sp.className='sprite';b.appendChild(sp);if(ICON[tile.type]){const label=document.createElement('span');label.className='label';label.textContent=ICON[tile.type];b.appendChild(label)}if(tile.level>1){const lv=document.createElement('small');lv.className='level';lv.textContent=`L${tile.level}`;b.appendChild(lv)}bindTile(b,i);mapEl.appendChild(b)});yearEl.textContent=state.year;moneyEl.textContent=`¥${state.money}`;populationEl.textContent=state.population.toLocaleString('ja-JP');incomeEl.textContent=`${state.income>=0?'+':''}¥${state.income}`;incomeEl.style.color=state.income<0?'#ff7568':'';modeLabel.textContent=LABEL[state.selected];modeHint.textContent=['road','rail'].includes(state.selected)?(state.pathStart===null?'起点をタップ':'終点をタップ。同じ場所で経路切替'):'マスをタップして設置';document.querySelectorAll('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===state.selected));save()}
function bindTile(el,i){const start=e=>{longPressed=false;pressTimer=setTimeout(()=>{longPressed=true;openRadial(i,e)},520)};const cancel=()=>clearTimeout(pressTimer);el.addEventListener('pointerdown',start);el.addEventListener('pointerup',e=>{cancel();if(!longPressed)tapTile(i)});el.addEventListener('pointercancel',cancel);el.addEventListener('contextmenu',e=>e.preventDefault());el.addEventListener('pointerenter',()=>{if(state.pathStart!==null&&['road','rail'].includes(state.selected)){preview=route(state.pathStart,i);render()}})}
function openRadial(i,e){radialEl.innerHTML='';['road','rail','station','power','water','park','bulldoze'].forEach(tool=>{const b=document.createElement('button');b.type='button';b.textContent=LABEL[tool];b.addEventListener('click',ev=>{ev.stopPropagation();state.selected=tool;state.pathStart=null;preview=[];radialEl.hidden=true;tapTile(i)});radialEl.appendChild(b)});const rect=mapEl.getBoundingClientRect(),p=xy(i),cell=rect.width/SIZE;radialEl.style.left=`${(p.x+.5)*cell}px`;radialEl.style.top=`${(p.y+.5)*cell}px`;radialEl.hidden=false}
document.addEventListener('pointerdown',e=>{if(!radialEl.hidden&&!radialEl.contains(e.target))radialEl.hidden=true});
function tapTile(i){updateTileInfo(i);radialEl.hidden=true;if(['road','rail'].includes(state.selected))return pathTap(i);if(state.selected==='bulldoze')return removeTile(i);placeSingle(i,state.selected)}
function pathTap(i){if(state.pathStart===null){state.pathStart=i;preview=[i];showMessage('終点をタップ');render();return}if(i===state.pathStart){state.pathMode=state.pathMode==='hv'?'vh':'hv';showMessage('経路を切り替えました');render();return}const cells=route(state.pathStart,i);const blocked=cells.filter(j=>!['empty',state.selected].includes(state.tiles[j].type));if(blocked.length){showMessage('途中に建物があります');state.pathStart=null;preview=[];return render()}const fresh=cells.filter(j=>state.tiles[j].type==='empty'),cost=fresh.length*COST[state.selected];if(state.money<cost){showMessage(`資金不足 ¥${cost}`);state.pathStart=null;preview=[];return render()}fresh.forEach(j=>state.tiles[j]={type:state.selected,level:1});state.money-=cost;showMessage(`${LABEL[state.selected]} ${fresh.length}マス建設`);state.pathStart=null;preview=[];render()}
function placeSingle(i,type){if(state.tiles[i].type!=='empty')return showMessage('空き地を選んでください');if(state.money<COST[type])return showMessage('資金不足');state.money-=COST[type];state.tiles[i]={type,level:1};showMessage(`${LABEL[type]}を建設`);render()}
function removeTile(i){const t=state.tiles[i];if(t.type==='empty')return showMessage('何もありません');if(BUILDINGS.includes(t.type)||['station','power','water'].includes(t.type)){if(!confirm(`${LABEL[t.type]||t.type}を撤去しますか？`))return}if(state.money<COST.bulldoze)return showMessage('資金不足');state.money-=COST.bulldoze;state.tiles[i]={type:'empty',level:0};showMessage('撤去しました');render()}
function growCity(){let built=0,upgraded=0;const order=[...state.tiles.keys()].sort(()=>Math.random()-.5);for(const i of order){const t=state.tiles[i];if(t.type==='empty'){const s=score(i);if(s<5||Math.random()>.48)continue;let type='house';if(supplied(i,'station',3)&&Math.random()<.38)type='shop';else if(supplied(i,'power',4)&&!supplied(i,'water',4)&&Math.random()<.5)type='factory';state.tiles[i]={type,level:1};built++;if(built>=Math.min(6,2+Math.floor(state.year/6)))break}else if(['house','shop','factory','apartment'].includes(t.type)&&score(i)>=7&&Math.random()<.28){t.level++;if(t.type==='house'&&t.level>=2)t.type='apartment';if(t.type==='apartment'&&t.level>=4)t.type='tower';upgraded++}}return{built,upgraded}}
function economy(){let pop=0,revenue=0,maintenance=0;for(const t of state.tiles){if(t.type==='house'){pop+=8*t.level;revenue+=2*t.level}if(t.type==='apartment'){pop+=25*t.level;revenue+=4*t.level}if(t.type==='tower'){pop+=65*t.level;revenue+=8*t.level}if(t.type==='shop'){pop+=4*t.level;revenue+=5*t.level}if(t.type==='factory'){pop+=3*t.level;revenue+=6*t.level}if(t.type==='road')maintenance+=.15;if(t.type==='rail')maintenance+=.25;if(t.type==='station')maintenance+=2;if(t.type==='power'||t.type==='water')maintenance+=3;if(t.type==='park')maintenance+=1}state.population=pop;state.income=Math.round(revenue-maintenance);state.money+=state.income}
function makeReport(r){if(!state.tiles.some(t=>t.type==='road'))return'道路をマップ端から街へつなげましょう。';if(!state.tiles.some(t=>t.type==='power'))return'発電所が必要です。選択すると供給範囲を確認できます。';if(!state.tiles.some(t=>t.type==='water'))return'水が不足しています。浄水場を建てましょう。';if(r.built===0&&r.upgraded===0)return'発展条件を満たす区画がありません。道路網と供給範囲を確認しよう。';return`新築 ${r.built}区画、成長 ${r.upgraded}区画。年間収支 ${state.income>=0?'+':''}¥${state.income}`}
function nextYear(){const r=growCity();economy();state.year++;reportEl.textContent=makeReport(r);showMessage(`YEAR ${state.year}`);render()}
document.querySelectorAll('.tool').forEach(b=>b.addEventListener('click',()=>{state.selected=b.dataset.tool;state.pathStart=null;preview=[];render()}));
$('nextYearBtn').addEventListener('click',nextYear);
$('resetBtn').addEventListener('click',()=>{if(!confirm('街を最初から作り直しますか？'))return;localStorage.removeItem('infra-king-save-v2');state=initial();preview=[];selectedTile=null;reportEl.textContent='道路を引き、電気と水を届けよう。';render()});
load();economy();render();